### ISSUE TITLE
slackbot -- whodis lookup breaks in PM's

### ISSUE THREAD

**Issue by lockefox** [EVEprosper/ProsperBots#1]
lookup info from `slackbot` breaks when responding to PM's

```python
failed to handle message version with plugin "which_prosperbot"
Traceback (most recent call last):
  File "/opt/venvs/prosper-bots/lib/python3.5/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/opt/venvs/prosper-bots/scripts/prosper_slackbot.py", line 33, in which_prosperbot
    message_info = slack_utils.parse_message_metadata(message)
  File "/opt/venvs/prosper-bots/lib/python3.5/site-packages/prosper_bots/slack_utils.py", line 19, in parse_message_metada
    metadata['channel_name'] = message_obj._client.channels[metadata['channel']]['name']
KeyError: 'name'
```

**Comment by lockefox** [comment]
fixed in v0.0.5
